# -*- coding: utf-8 -*-
"""productt review

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148TxtR0hqWPHvJznx7soZg5Qk5elqi1i
"""

from transformers import pipeline
import pandas as pd

#Load Sentiment analysis model
sentiment = pipeline("sentiment-analysis")

#sample product review(you can change only this text later)
reviews = """The laptop starts quickly and works smoothly for daily tasks.
The screen quality is clear and good for watching video.
Battery backup is average and needs charging often.
The ten makes noisewhen many apps are running.
Overall, it is a good laptop for students but not the gaming
"""

#split review into sentences
sentences = reviews.split(".")

pros = [ ]
cons = [ ]

for s in sentences:
  s = s.strip()
  if s == "":
        continue

  result=sentiment(s)[0]


  if result["label"] == "POSITIVE":
    pros.append(s)
  elif result["label"] == "NEGATIVE":
    cons.append(s)

#take only 2 pros and 2 cons
pros = pros[:2]
cons = cons[:2]

#create table
df=pd.DataFrame({
    "pros":pros,
    "cons":cons
})